export default {
  mysql: 'mysql',
  mariadb: 'mariadb',
  postgres: 'postgres',
  cockroachdb: 'cockroachdb',
  sqlite: 'sqlite',
  mssql: 'mssql',
  sap: 'sap',
  oracle: 'oracle',
  cordova: 'cordova',
  nativescript: 'nativescript',
  'react-native': 'react-native',
  sqljs: 'sqljs',
  mongodb: 'mongodb',
  'aurora-mysql': 'aurora-mysql',
  'aurora-postgres': 'aurora-postgres',
  expo: 'expo',
  spanner: 'spanner',
};
